The Nextt Web Magazine clone: Responsive Design
mke2111/TNW-Clone pull request #2
Opened 2020-09-30 01:02 UTC by alejandrotoledoweb

Contains:
-Flexbox, grids and float elements
-Used media query for responsive and different screen sizes
-Includes all elements on the original page

2020-09-30 01:28 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-30 01:44 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @alejandrotoledoweb and @mke2111
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Remove commented css from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [ ] Use `article` tag properly
- [ ] Margin of `main` tag effecting the navbar. Please fix the margin-top issue
### Navbar
- [ ] Remove **GET TICKETS** button from small screens
- [ ] Logo should not overflow on the sub-navbar


|[Source Page](https://thenextweb.com/)|[Clone Page](https://rawcdn.githack.com/mke2111/TNW-Clone/4ce29eedd4b895dd1c662492c70781430d1f67d0/index.html)|
|:---:|:---:|
|![onav](https://user-images.githubusercontent.com/29689273/94633789-d342bf80-02e7-11eb-9791-b51ea9bdffc9.png)|![c-nav478](https://user-images.githubusercontent.com/29689273/94633790-d473ec80-02e7-11eb-96c5-ef0efd84fa65.png)|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-30 01:44 UTC, umairarshadbutt commented on styles.css
> +.nn {
Remove commented css

2020-09-30 01:44 UTC, umairarshadbutt commented on styles.css
> +  /* .main-news {
Remove commented CSS

2020-09-30 01:44 UTC, umairarshadbutt commented on styles.css
> +  /* main {
Remove commented CSS

2020-09-30 01:44 UTC, umairarshadbutt commented on index.html
> +      <div class="big-picture v-flex">
It should be an `article`

2020-09-30 01:44 UTC, umairarshadbutt commented on index.html
> +      <div class="side-pic d-flex a-top">
It should be an `article`

2020-09-30 01:44 UTC, umairarshadbutt commented on index.html
> +      <div class="side-pic d-flex b-bottom">
It should be an `article`

2020-09-30 13:29 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @alejandrotoledoweb and @mke2111
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Fix the Linter issues
- [ ] Use `article` tag properly (As we discussed in call)


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-30 14:45 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello!! Great effort on the project!

## Required Changes
### [Mandatory] :red_circle: 

- [ ] Navbar its looking distorted on desktop screen size min 1024px
![image](https://user-images.githubusercontent.com/25774518/94697794-38a1ab00-02fe-11eb-85e0-0347e32e9dc0.png)

- [ ] Original website only has a 4 column lates news section
![image](https://user-images.githubusercontent.com/25774518/94700917-a7343800-0301-11eb-8d3b-b45d00892fa2.png)

- [ ] Latest funding doesn't match original at 1024px
![image](https://user-images.githubusercontent.com/25774518/94697983-70a8ee00-02fe-11eb-9e9e-6479e799eadf.png)
**and 1440px**
![image](https://user-images.githubusercontent.com/25774518/94698048-861e1800-02fe-11eb-89d6-aeaf3d8d78c6.png)

- [ ] Category section is not matching original at 1024px
![image](https://user-images.githubusercontent.com/25774518/94698335-d006fe00-02fe-11eb-82e7-df2dd7abc645.png)

- [ ] Footer has a white space on the right on mobile version

- [ ] Footer does not match the style of the original
![image](https://user-images.githubusercontent.com/25774518/94698540-09d80480-02ff-11eb-9e20-239c990575cd.png)

- [ ] Latest funding show only 3 elements in mobile

- [ ] Latest funding has extra white space to the right
![image](https://user-images.githubusercontent.com/25774518/94699268-c4680700-02ff-11eb-96b8-c3f882040811.png)

- [ ] 3 image section is lacking white space to the right
![image](https://user-images.githubusercontent.com/25774518/94699225-b3b79100-02ff-11eb-9ce7-11fb779f8dae.png)


### [OPTIONAL]  :large_blue_circle: 

- [ ] The project should follow this structure. Having a directory for the css, the images and javascript files.
```
/
  css/
    style.css
  img/
    ... some images...
  js/
     ... some scripts...
  index.html
```

- [ ] Choose meaningful names for the CSS selectors. This improves readability and helps the programmer to keep track of fewer things in his mind.
**Actual**: 
```
.nn {
  ... some properties...
}
```
```
.navbar__menu {
  ... some properties...
}
```

- [ ] Use the media query browser inspector to compare the clone with the original. This will give a broad understanding of the project and will show if the clone looks as intended in different screen sizes.


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-30 17:08 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello team!
Good job with the projects and the changes made! 👍 
Now the linters are green 🟢 

However, we still need to do some change before the approving the project and move forward ⏩ 
Kindly, check my comments below 👇  apply the changes and resubmit for a new code review

Good luck, guys! 😃 

- Kindly change the first section to 'latest news', now the title is 'latest deals'
- Navbar should be fixed or sticky
- Kindly update your live link before request for a code review

- At 1024px
   - Latest news section and latest deals sections should not have that much margin in the right, please make it equal to the original.
   - Latest fundings links(add info, see more...) must be inline, kindly modify it
   - The section after latest findings is overlapping one item with the other, please adjust the margins
- at 768px
   - latest fundings must have 1 item per row, kindly modify it
   - In the hard fork section, the first item, the latest section must be aligned left, please modify it
   - In the hard fork section, on the rest of the items, the latest section image must be aligned to the right
   - Please modify the footer so it takes all the width of the screen.

2020-09-30 17:52 UTC, javitocor requested changes
#STATUS CHANGES REQUIRED ♻️ 

Team, good job so far with this project! 👍 
But still some code to fix to getting approved
Please, check my comments below 👇  and resubmit for a new code review when they are done 💪 

- The navbar is overlapping the content in medium and small devices, please fix it
- In small screens, the latest findings section must have a margin between items and should not have that big margin on the right side, please modify it and make it equal to the original.
- In small screens, the hard fork section, on the latest sections still have problems with the positioning, the image must be aligned right and the text must be aligned left in all items.
- The second latest news must be latest deals
- In the latest deals section kindly add the discount on the upper right corner

2020-09-30 17:52 UTC, javitocor commented on styles.css
> +    display: grid;
maybe the problem with the footer comes from here, try to make it 100%

2020-09-30 17:52 UTC, javitocor commented on styles.css
> +    width: 18rem;
maybe the problem with this section comes from here, try to modify the width to 100% and align the text to the right

2020-09-30 20:48 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far. However, there are some changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

**_The main point of this project is to implement a Responsive Web Design. Therefore, we have to put emphasis on how it behaves on different screen sizes where the website is rendered_**

**At mobile screen sizes:**

- [ ] You're having some alignment issues in the `Hard Fork` section.

Source page:
![21:34:09](https://user-images.githubusercontent.com/26856491/94736805-b9938d80-0364-11eb-9671-046c943a7fdd.png)

Your page:
![21:33:40](https://user-images.githubusercontent.com/26856491/94736818-bef0d800-0364-11eb-99e6-fb88da51af8e.png)

- A similar case is observed in the `Apps`, `Gear`, `Tech`, `Creative`, `Podium`, `Insights`, `Launch`, and `Distract` sections too. Kindly fix it.

Source page:
![21:35:50](https://user-images.githubusercontent.com/26856491/94737038-155e1680-0365-11eb-9d9e-802e0b02be11.png)

Your page:
![21:36:18](https://user-images.githubusercontent.com/26856491/94737058-1abb6100-0365-11eb-897b-03873e2793ad.png)

- [ ] The `Latest Funding Rounds` section is having more space to the right than the left. Kindly fix this.

Source page:
![21:45:48](https://user-images.githubusercontent.com/26856491/94737866-7803e200-0366-11eb-99b9-22727f57689b.png)

Your page:
![21:46:50](https://user-images.githubusercontent.com/26856491/94737877-7afed280-0366-11eb-90b9-b2c2ff7a05e8.png)


**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-09-30 21:57 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @alejandrotoledoweb & @mke2111  :wave:

__I commend your efforts in implementing changes requested so far. The project is almost there, just some minor adjustments and we should be ready to go.__

**[ REQUIRED CHANGES ]**

_We have to make sure that everything is how they should be. It's a bit challenging to figure out all these changes at once because one thing is leading to another in this project._

**At 768px screen size**

- [ ] We are still having some whitespace issues in the `Latest Funding` section.

Source Page:
![22:40:11](https://user-images.githubusercontent.com/26856491/94742756-1e9fb100-036e-11eb-95cb-ffab43a8bdf4.png)

Your Page:
![22:41:10](https://user-images.githubusercontent.com/26856491/94742767-23646500-036e-11eb-9d54-13ba2fd094c7.png)

**At large screen size**

- [ ] The `Latest Funding` section is having some spaces different from the original page.
- Using `display: flex` for the latest fundings container might solve this problem.

Source page:
![22:49:53](https://user-images.githubusercontent.com/26856491/94743430-49d6d000-036f-11eb-9fa3-624ef931b171.png)

Your page:
![22:48:50](https://user-images.githubusercontent.com/26856491/94743441-4d6a5700-036f-11eb-823a-9d7223cfd331.png)


**[ COMMENTS ]**
- I believe that most of these issues you are having can be traced back to the way you approach the implementation. 
- Using Grid/Flex for the containers of each section, most especially the ones we've been talking about, might really be of help. If they're properly used, Grid/Flex helps in justifying and aligning their contents the way we want them.

**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-01 01:53 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @alejandrotoledoweb and @mke2111
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes  👇.
- [ ] The Latest Funding Rounds section is having more space to the right than the left. Kindly fix this.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-01 03:32 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Team, good job with the implementation of the required changes! 👍 
But we still need to implement some more to get the project approved 💪 
Please, implement all the changes before for all screen sizes, make your project looks similar to the original, and then and only then request for a new code review.
Check my comments below 👇 

Good luck, guys! 😃 

- Large screens
   - latest fundings section must have the same width as latest news, latest deals and hard-fork section. Please fix it.
   - In the latest deals section, please add the yellow discount banner on the upper right side of the image.
- 1024px
   - Please remove the horizontal scrollbar
   - Latest foundation section width must have almost the full width of the screen, please centre it and give it the proper width.
   - Latest deals and latest news sections must have 3 items per row.
- at 768px:
  - please remove the horizontal scrollbar
   - Latest fundings section, the items must fit on the screen, now there is too much space in the right and left sides

2020-10-01 11:12 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-10-01 11:17 UTC, umairarshadbutt approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://rawcdn.githack.com/mke2111/TNW-Clone/98426bad9c0ea29af58e63f79c5dd2ea26ec093e/index.html) shows a good understanding of Building with Responsive Design. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @alejandrotoledoweb and @mke2111! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-01 11:20 UTC, merged